version: '3'
services:

  app:
    build:
      context: ./node
    image: renanmattos/app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: ./nginx
    image: renanmattos/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app
    entrypoint: dockerize -wait tcp://app:3000 -timeout 10s /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    restart: always

  db:
    image: mysql:5.7
    user: mysql
    command:
      --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    networks:
      - node-network

volumes:
  db_data:
    driver: local

networks:
  node-network:
